env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
ignorePatterns:
  - "*.config.js"
rules: 
  no-plusplus: off
  no-unused-vars: warn
  no-loss-of-precision: warn
  no-param-reassign: warn
  no-console: off
